version: "3.8"

services:
  spring-boot-app:
    build:
      dockerfile: Dockerfile
    container_name: spring-boot-app-container
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgresql-db
    environment:
      - WAIT_HOSTS=postgresql-db:5432
      - WAIT_HOSTS_TIMEOUT=600
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=60


  postgresql-db:
    image: postgres:latest
    container_name: postgresql-db-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test123
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kanbanDB